# Generated by Django 4.2.3 on 2023-08-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_quesmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
